{
 "title": "Airflow DAGs Overview",
 "description": "A simple dashboard to monitor Apache Airflow DAGs — track total DAGs, last run status, execution durations, and success/failure trends across instances.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "dag_id",
    "label": "DAG ID",
    "query": {
     "query": "label_values(airflow_dag_last_status, dag_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DAG Last Run Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (dag_id, status) (airflow_dag_last_status{dag_id=~\"$dag_id\"}) == 1"
    }
   ]
  },
  {
   "title": "DAGs Information with Run Counts",
   "type": "table",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (dag_id, instance, owner) (airflow_dag_status{dag_id=~\"$dag_id\"})"
    },
    {
     "expr": "sum by (dag_id) (airflow_dag_status{dag_id=~\"$dag_id\", status=\"success\"})",
     "legendFormat": "Total Success"
    },
    {
     "expr": "sum by (dag_id) (airflow_dag_status{dag_id=~\"$dag_id\", status=\"failed\"})",
     "legendFormat": "Total Failed"
    },
    {
     "expr": "last_over_time(airflow_dag_run_duration{dag_id=~\"$dag_id\"}[1d])"
    }
   ]
  },
  {
   "title": "Retry task",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (dag_id) (\r\n  airflow_task_status{dag_id=~\"$dag_id\", status=\"up_for_retry\"}\r\n)",
     "legendFormat": "{{dag_id}} / {{task_id}}"
    }
   ]
  },
  {
   "title": "Sucess task %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_task_status{status=\"success\"})\r\n/\r\nsum(airflow_task_status)\r\n* 100",
     "legendFormat": "{{dag_id}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (dag_id)(\r\n  rate(airflow_dagrun_schedule_delay_sum{dag_id=~\"$dag_id\"}[1h])\r\n)\r\n/\r\nsum by (dag_id)(\r\n  rate(airflow_dagrun_schedule_delay_count{dag_id=~\"$dag_id\"}[1h])\r\n)\r\n",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Success / Failed Dags count per day",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (dag_id) (\r\n  increase(airflow_dagrun_duration_success_count{dag_id=~\"$dag_id\"}[1d])\r\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(airflow_dagrun_duration_failed_count[1d])) by (dag_id)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Overall Success Rate / 1d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(airflow_dagrun_duration_success_count[1d])) \r\n  / sum(increase(airflow_dagrun_duration_success_count[1d])\r\n      + increase(airflow_dagrun_duration_failed_count[1d])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DAGs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (dag_id) (airflow_dag_last_status))"
    }
   ]
  }
 ]
}