{
 "title": "Airflow DAG dashboard",
 "description": "https://github.com/databand-ai/airflow-dashboards, with multi cluster support",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dag_id",
    "label": "DAG ID",
    "query": {
     "query": "label_values(af_agg_dagrun_dependency_check{cluster=\"$cluster\"},dag_id)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(af_agg_dag_processing_duration,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DAG stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success DAG run duration",
     "type": "timeseries",
     "description": "Seconds taken for a DagRun to reach success state",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "af_agg_dagrun_duration_success{dag_id=\"$dag_id\",cluster=\"$cluster\"}",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "Failed DAG run duration",
     "type": "timeseries",
     "description": "Seconds taken for a DagRun to reach failed state",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "af_agg_dagrun_duration_failed{dag_id=\"$dag_id\",cluster=\"$cluster\"}",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "DAG run duration",
     "type": "timeseries",
     "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (dag_id, quantile) (af_agg_dag_task_duration{dag_id=\"$dag_id\",cluster=\"$cluster\"})",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "DAG run dependency check time",
     "type": "timeseries",
     "description": "Seconds taken to check DAG dependencies",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "af_agg_dagrun_dependency_check{dag_id=\"$dag_id\",cluster=\"$cluster\"} * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "DAG run schedule delay",
     "type": "timeseries",
     "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "af_agg_dagrun_schedule_delay{dag_id=\"$dag_id\",cluster=\"$cluster\"} * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "Event Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(statsd_exporter_events_total{}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}