{
 "title": "data quality",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Null ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Null ratio",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pg_data_quality_null_ratio_char_count_null_ratio",
     "legendFormat": "char_count"
    },
    {
     "expr": "pg_data_quality_null_ratio_content_null_ratio",
     "legendFormat": "content"
    },
    {
     "expr": "pg_data_quality_null_ratio_language_null_ratio",
     "legendFormat": "language"
    },
    {
     "expr": "pg_data_quality_null_ratio_source_null_ratio",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "pg_data_quality_null_ratio_thai_null_ratio",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "pg_data_quality_null_ratio_type_null_ratio",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "pg_data_quality_null_ratio_word_count_null_ratio",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current record",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_data_quality_records_records_cleaned",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "RECORD PER BATCH /1d",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_data_quality_records_per_batch_records_cleaned",
       "legendFormat": "{{dataset_name}}"
      }
     ]
    },
    {
     "title": "New panel",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum by (dataset_name, batch_day) (\r\n  pg_data_quality_records_per_batch_records_cleaned\r\n)",
       "legendFormat": "{{dataset_name}}"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum by (dataset_name, batch_day) (\r\n  pg_data_quality_records_per_batch_records_cleaned\r\n)",
       "legendFormat": "{{dataset_name}}"
      }
     ]
    }
   ]
  }
 ]
}