{
 "title": "MinIO Bucket Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (\r\n  minio_bucket_usage_total_bytes\r\n) / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_usage_total_bytes{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "Usage [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range) (minio_bucket_objects_size_distribution{job=\"minio-bucket\"})",
     "legendFormat": "{{bucket}} - {{range}}"
    }
   ]
  },
  {
   "title": "Object Version Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,range) (minio_bucket_objects_version_distribution{job=\"minio-bucket\"})",
     "legendFormat": "{{bucket}}-{{range}}"
    }
   ]
  },
  {
   "title": "TTFB Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (bucket,le,api) (minio_bucket_requests_ttfb_seconds_distribution{job=\"minio-bucket\"})",
     "legendFormat": "{{bucket}}-{{le}}-{{api}}"
    }
   ]
  },
  {
   "title": "Last Hour Failed Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_replication_last_hour_failed_bytes{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "Last Hour Failed Size [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Total Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (bucket,api) (increase(minio_bucket_requests_total{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}-{{api}}"
    }
   ]
  },
  {
   "title": "Total Data Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_traffic_received_bytes{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Inflight Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (bucket,api) (increase(minio_bucket_requests_inflight_total{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket,api}}"
    }
   ]
  },
  {
   "title": "Versions Increase Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (bucket) (increase(minio_bucket_usage_version_total{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Total Data Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(minio_bucket_traffic_sent_bytes{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{bucket}}]"
    }
   ]
  },
  {
   "title": "Delete Markers Increase Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (bucket) (increase(minio_bucket_usage_deletemarker_total{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Objects Increase Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (bucket) (increase(minio_bucket_usage_object_total{job=\"minio-bucket\"}[$__rate_interval]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicated Out Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_sent_count{job=\"minio-bucket\"})",
       "legendFormat": "Replicated Out Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replicated In Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_received_count{job=\"minio-bucket\"})",
       "legendFormat": "Replicated In Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Data Sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_sent_bytes{job=\"minio-bucket\"})",
       "legendFormat": "Replication Data Sent [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Data Received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_received_bytes{job=\"minio-bucket\"})",
       "legendFormat": "Data Received [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Latency (millis)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by (bucket,operation) (minio_bucket_replication_latency_ms{job=\"minio-bucket\"})",
       "legendFormat": "{{bucket}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Replication Failed Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_total_failed_count{job=\"minio-bucket\"})",
       "legendFormat": "Replication Failed Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Data Failed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_total_failed_bytes{job=\"minio-bucket\"})",
       "legendFormat": "Replication Failed [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Minute Failed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(minio_bucket_replication_last_minute_failed_bytes{job=\"minio-bucket\"}[$__rate_interval]))",
       "legendFormat": "Last Minute Failed Size [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Minute Failed Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_last_minute_failed_count{job=\"minio-bucket\"})",
       "legendFormat": "Last Minute Failed Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Hour Failed Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_last_hour_failed_count{job=\"minio-bucket\"})",
       "legendFormat": "Last Hour Failed Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Total Failed Proxied Get Tag Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minio_bucket_replication_proxied_get_tagging_requests_failures{job=\"minio-bucket\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Proxied Head Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_proxied_head_requests_total{job=\"minio-bucket\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Total Failed Proxied Put Tag Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minio_bucket_replication_proxied_put_tagging_requests_failures{job=\"minio-bucket\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Failed Proxied Head Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minio_bucket_replication_proxied_head_requests_failures{job=\"minio-bucket\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Proxied Delete Tag Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_proxied_delete_tagging_requests_total{job=\"minio-bucket\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Total Proxied Get Tag Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_proxied_get_tagging_requests_total{job=\"minio-bucket\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Total Proxied Put Tag Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_proxied_put_tagging_requests_total{job=\"minio-bucket\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Total Failed Proxied Delete Tag Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minio_bucket_replication_proxied_delete_tagging_requests_failures{job=\"minio-bucket\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Failed Proxied Get Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minio_bucket_replication_proxied_get_requests_failures{job=\"minio-bucket\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Proxied Get Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_proxied_get_requests_total{job=\"minio-bucket\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}