{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(pg_up{release=\"$release\"})"
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "stat",
     "description": "start time of the process",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_postmaster_start_time_seconds{release=\"$release\", instance=\"$instance\"} * 1000"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{release=\"$release\", datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{release=\"$release\", instance=\"$instance\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Table_size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_table_size_bytes{instance=\"$instance\"}\r\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "tablesizeGrowth",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  max_over_time(pg_stat_user_tables_table_size_bytes{instance=\"$instance\"}[1d])\r\n-\r\n  min_over_time(pg_stat_user_tables_table_size_bytes{instance=\"$instance\"}[1d]),\r\n  0\r\n)",
     "legendFormat": "{{datname}}-{{relname}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{instance=\"$instance\", datname=~\"$datname\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Connection Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  pg_stat_database_numbackends{instance=\"$instance\", datname=~\"$datname\"}\r\n)\r\n/\r\non (instance)\r\npg_settings_max_connections{instance=\"$instance\"}\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table_Size_Growth all_time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_table_size_bytes{instance=\"$instance\"}[1d])\r\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Insert rate (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n",
     "legendFormat": "{{datname}} inserts"
    }
   ]
  },
  {
   "title": "Update rate (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n",
     "legendFormat": "{{datname}} updates"
    }
   ]
  },
  {
   "title": "AVG query time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(pg_stat_database_active_time_seconds_total{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n)\r\n/\r\nsum(\r\n  rate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m]) +\r\n  rate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n)\r\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max query time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_max_tx_duration{instance=\"$instance\", datname=~\"$datname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max query time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_max_tx_duration{instance=\"$instance\", datname=~\"$datname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  3,\r\n  rate(pg_stat_statements_seconds_total{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n  /\r\n  rate(pg_stat_statements_calls_total{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n)",
     "legendFormat": "{{datname}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "query rate 5m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  rate(pg_stat_statements_calls_total{instance=\"$instance\", datname=~\"$datname\"}[5m])\r\n)",
     "legendFormat": "{{datname}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "query read/write( row/s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  pg_stat_statements_rows_total{instance=\"$instance\", datname=~\"$datname\"}\r\n)",
     "legendFormat": "{{datname}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "query call count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  pg_stat_statements_calls_total{instance=\"$instance\", datname=~\"$datname\"}\r\n)",
     "legendFormat": "{{datname}}-{{queryid}}"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\"} != 0",
       "legendFormat": "{{datname}},{{mode}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "timeseries",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{instance=\"$instance\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{instance=\"$instance\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  }
 ]
}